package SoseL21.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Boolean = 0;
  public static final int EmptyStatement = 1;
  public static final int Integer = 2;
  public static final int Reference = 3;
  public static final int SoSeWorksheet = 4;
  public static final int Statement = 5;
  public static final int Variable = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe5e1a54d7b5f41a7L, 0x9d2d73de1700459bL);
    builder.put(0x4c875829485576a8L, Boolean);
    builder.put(0x4c87582948540e5aL, EmptyStatement);
    builder.put(0x4c875829485576a7L, Integer);
    builder.put(0x4c875829485576a9L, Reference);
    builder.put(0x7f0bd6aaa6578930L, SoSeWorksheet);
    builder.put(0x7f0bd6aaa6584379L, Statement);
    builder.put(0x7f0bd6aaa6584016L, Variable);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
